# Power Button
bind = , XF86PowerOff, exec, ~/.config/rofi/scripts/powermenu_t1
bindl = SHIFT, XF86PowerOff, exec, systemctl suspend

# Keyboard Power Button
bind = , XF86TouchpadOn, exec, ~/.config/rofi/scripts/powermenu_t1
bindl = SHIFT, XF86TouchpadOn, exec, systemctl suspend
bindl = CTRL, XF86TouchpadOn, exec, loginctl lock-session
