// This file was autogenerated using matugen
// All the colors detected by matugen are included here
pragma Singleton

import QtQuick
import Quickshell

Singleton {
    <* for name, value in colors *> readonly property color {{ name }}: "{{ value.default.hex }}"
    <* endfor *>
}

